import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script
          src="https://accounts.google.com/gsi/client"
          async
          defer
        ></script>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              window.onload = function () {
                google.accounts.id.initialize({
                  client_id: '219903509938-h6nvmjjaj4b457o2duau06cicua1slv8.apps.googleusercontent.com',
                  callback: handleCredentialResponse
                });
                google.accounts.id.renderButton(
                  document.getElementById("g-signin2"),
                  { theme: "outline", size: "large" }
                );
                google.accounts.id.prompt();
              };

              function handleCredentialResponse(response) {
                console.log("Encoded JWT ID token: " + response.credential);
                fetch('/tokensignin', {
                  method: 'POST',
                  headers: {
                    'Content-Type': 'application/json'
                  },
                  body: JSON.stringify({ id_token: response.credential })
                }).then(response => {
                  return response.json();
                }).then(data => {
                  console.log(data); // Datos del usuario
                });
              }
            `,
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <h2>Me gusta la fafafa mi locro</h2>
        <div id="g-signin2"></div>
      </body>
    </html>
  );
}
